import json
import time
from pathlib import Path

import streamlit as st
import streamlit.components.v1 as components


def cleanup_old_transcripts(transcript_dir: Path, max_age_hours: int = 24) -> int:
    """Delete transcript files older than the configured retention window."""
    if not transcript_dir.exists():
        return 0

    cutoff_ts = time.time() - (max_age_hours * 3600)
    deleted_count = 0

    for transcript_file in transcript_dir.glob("*.txt"):
        try:
            if transcript_file.stat().st_mtime < cutoff_ts:
                transcript_file.unlink()
                deleted_count += 1
        except OSError:
            continue

    return deleted_count


def list_transcript_files(transcript_dir: Path) -> list[Path]:
    """Return transcript text files sorted by newest first."""
    if not transcript_dir.exists():
        return []

    files = [path for path in transcript_dir.glob("*.txt") if path.is_file()]
    return sorted(files, key=lambda path: path.stat().st_mtime, reverse=True)


def render_copy_button(text: str, button_id: str) -> None:
    """Render a browser-side copy button for transcript text."""
    js_text = json.dumps(text)
    components.html(
        f"""
        <button id="{button_id}" style="padding:8px 14px; border-radius:8px; border:1px solid #c9ced6; background:#ffffff; cursor:pointer;">Copy Text</button>
        <script>
        const textToCopy = {js_text};
        const copyBtn = document.getElementById({json.dumps(button_id)});
        copyBtn.addEventListener("click", async () => {{
            try {{
                await navigator.clipboard.writeText(textToCopy);
                copyBtn.textContent = "Copied";
                setTimeout(() => copyBtn.textContent = "Copy Text", 1500);
            }} catch (error) {{
                copyBtn.textContent = "Copy failed";
                setTimeout(() => copyBtn.textContent = "Copy Text", 1800);
            }}
        }});
        </script>
        """,
        height=52,
    )


st.set_page_config(page_title="Generated Text", page_icon="📝", layout="centered")

st.title("Generated Text")
st.write("View and copy transcript text files generated by the Home page.")

transcripts_dir = Path("downloads") / "transcripts"

deleted_transcripts = cleanup_old_transcripts(transcripts_dir, max_age_hours=24)
if deleted_transcripts > 0:
    st.info(f"Auto-cleanup removed {deleted_transcripts} old transcript file(s).")

st.caption("Transcript files are kept for 1 day and then deleted automatically.")

transcript_files = list_transcript_files(transcripts_dir)

if not transcript_files:
    st.warning("No transcript files available yet.")
else:
    transcript_names = [path.name for path in transcript_files]

    selected_name = st.selectbox(
        "Select transcript file",
        options=transcript_names,
        index=0,
    )

    selected_path = transcripts_dir / selected_name
    if selected_path.exists():
        transcript_text = selected_path.read_text(encoding="utf-8")
        st.subheader("Resulting Text")
        st.text_area("Transcript", transcript_text, height=320)
        render_copy_button(transcript_text, button_id="copy-transcript-page")
        st.download_button(
            label="Download Transcript (.txt)",
            data=transcript_text,
            file_name=selected_path.name,
            mime="text/plain",
        )
